### PR TITLE
Update Volunteer Page

### PR DESCRIPTION
**Pull request by mel-d**
Waiting on a headshot from Mary Clare!

### CODE REVIEW

**Review by Gmfholley — APPROVED** [review]

**Comment by Gmfholley** [comment]
Changes look good.  Waiting for Mary Clare's headshot to merge.

**Comment by mel-d** [comment]
> Changes look good. Waiting for Mary Clare's headshot to merge.

@Gmfholley, just got that headshot up in case you wanted to take a last look before merge!

**Comment by Gmfholley** [comment]
@mel-d Did mary clare's headshot get added to the commit?  I don't see it in the diff yet. 🤔

**Comment by mel-d** [comment]
> @mel-d Did mary clare's headshot get added to the commit? I don't see it in the diff yet. 🤔

OH NOOOO the curse of `git add -p`

**Comment by Gmfholley** [comment]
Looks great!

**Pull request merged**
